pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.image('maven:3.8.6').inside {
                        sh 'mvn -B -DskipTests clean package'
                    }
                }
            }
        }
    }
}
