pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    git(
                        branch: 'master',
                        url: 'https://github.com/imabhosale/simple-java-maven-app.git'
                    )
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
